<?php

/**
 * @file
 *    Custom functionality for a jir sms settings
 */

function jir_stats_block_info()
{
    $blocks['jir_stats'] = array(
        'info' => t('JIR Jobs Counter'),
    );

    $blocks['jir_realtime'] = array(
        'info' => t('Realtime Figures'),
    );

    $blocks['jir_copyright'] = array(
        'info' => t('JIR Copyright'),
    );
    return $blocks;
}

function jir_stats_block_view($delta = '')
{

    $block = array();

    switch ($delta) {
        case 'jir_realtime':
            $query = new EntityFieldQuery();
            $query->entityCondition('entity_type', 'node')->entityCondition('bundle', 'employer')->propertyCondition('status', 1)->count();
            $result = $query->execute();
            $url = "http://search.jobinrwanda.com/api/stats";
            $request = drupal_http_request($url);
            $json_response = drupal_json_decode($request->data);

            $employers = number_format($result, 0, '.', ',');
            $jobs_published = number_format($json_response['totalJobs'], 0, '.', ',');
            $registered_candidates = number_format($json_response['totalApplications'], 0, '.', ',');

            $out = '<ul class="list-group"><li class="list-group-item">Employers <span class="badge">'. $employers .'</span></li>';
            $out .= '<li class="list-group-item">Jobs published since 2012 <span class="badge">'. $jobs_published .'</span></li>';
            $out .= '<li class="list-group-item">Job candidates registered <span class="badge">'. $registered_candidates .'</span></li></ul>';

            $block['subject'] = t('Realtime Figures');
            $block['content'] = $out;
            break;

        case 'jir_copyright':
            $year = date("Y");
            $site_name = filter_xss_admin(variable_get('site_name', 'Drupal'));
            $out = "<p>Copyright &copy " . $year . " " . $site_name . " Ltd. All Rights Reserved.<br /><a href='/content/job-rwanda-terms-use'>Terms of use</a> | <a href='/content/job-rwanda-privacy-policy'>Privacy policy</a> | <a href='/user'>Administration</a></p>";
            $block['subject'] = t('JIR Copyright');
            $block['content'] = $out;
            break;
    }
    return $block;
}


/**
 * Implements hook_field_widget_form_alter().
 */

function jir_stats_field_widget_form_alter(&$element, &$form_state, $context) {
    /**
     * Make sure we are not under admin path
     */
    if (arg(0) != 'admin'
        and $context['field']['type'] == 'entityreference'
        and $context['field']['field_name'] == 'field_employer') {

        /**
         * Autocomplete may behave differently than other widgets, so we check that first
         */
        if (isset($element['target_id'])) {
            $element['target_id']['#element_validate'][] = '_nonEmptyEmployerReferenceValidator';
        } else {
            $element['#element_validate'][] = '_nonEmptyEmployerReferenceValidator';
        }
    }
}

function _nonEmptyEmployerReferenceValidator($element, &$form_state, $form) {

    /**
     * Check whether the value in Company name field is empty or matches e.g: abocdef (1234)
     */
    $valid = empty($element['#value']) || preg_match("'\w*\s\(\d{1,}\)$'", $element['#value']);
    if (!$valid) {
        form_set_error('field_employer', 'Invalid employer name.');
        watchdog('Fake Job', t('Fake job attempt. Wrong employer name: %name'),
            array('%name' => $element['#value']), WATCHDOG_ERROR);
    }
}