<?php

/**
 * @file
 *    Custom functionality for a jir sms settings
 */

function jir_stats_block_info()
{
    $blocks['jir_stats'] = array(
        'info' => t('JIR Jobs Counter'),
    );

    $blocks['jir_realtime'] = array(
        'info' => t('Realtime Figures'),
    );

    $blocks['jir_copyright'] = array(
        'info' => t('JIR Copyright'),
    );
    return $blocks;
}

function jir_stats_block_view($delta = '')
{

    $block = array();

    switch ($delta) {
        case 'jir_realtime':
            $query = new EntityFieldQuery();
            $query->entityCondition('entity_type', 'node')->entityCondition('bundle', 'employer')->propertyCondition('status', 1)->count();
            $result = $query->execute();
            $url = "http://search.jobinrwanda.com/api/stats";
            $request = drupal_http_request($url);
            $json_response = drupal_json_decode($request->data);

            $employers = number_format($result, 0, '.', ',');
            $jobs_published = number_format($json_response['totalJobs'], 0, '.', ',');
            $registered_candidates = number_format($json_response['totalApplications'], 0, '.', ',');

            $out = '<ul class="list-group"><li class="list-group-item">Employers <span class="badge">'. $employers .'</span></li>';
            $out .= '<li class="list-group-item">Jobs published since 2012 <span class="badge">'. $jobs_published .'</span></li>';
            $out .= '<li class="list-group-item">Job candidates registered <span class="badge">'. $registered_candidates .'</span></li></ul>';

            $block['subject'] = t('Realtime Figures');
            $block['content'] = $out;
            break;

        case 'jir_copyright':
            $year = date("Y");
            $out = "<p>Copyright &copy " . $year . " Job in Rwanda JIR Ltd. All Rights Reserved.<br /><a href='/content/job-rwanda-terms-use'>Terms of use</a> | <a href='/content/job-rwanda-privacy-policy'>Privacy policy</a> | <a href='/user'>Administration</a></p>";
            $block['subject'] = t('JIR Copyright');
            $block['content'] = $out;
            break;
    }
    return $block;
}

/**
 * Implements hook_field_widget_form_alter().
 */
function jir_stats_field_widget_form_alter(&$element, &$form_state, $context) {
    if (arg(0) != 'admin'
        and $context['field']['type'] == 'entityreference'
        and $element['field_name'] == 'field_employer') {

        if (isset($element['target_id'])) {
            $element['target_id']['#element_validate'][] = 'nonEmptyEmployerReferenceValidator';
        } else {
            $element['#element_validate'][] = 'nonEmptyEmployerReferenceValidator';
        }
    }
}

function nonEmptyEmployerReferenceValidator($element, &$form_state, $form) {

    dpm($element['#value']);

    $valid = FALSE;

    if (!$valid) {
        form_error($form[$element['#field_employer']], t('Invalid employer name.'));
    }
}